/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/posts/{post-id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 게시물 조회
         * @description 게시물을 조회합니다.
         */
        get: operations["getPost"];
        /**
         * 게시물 수정
         * @description 게시물을 수정합니다.
         */
        put: operations["updatePost"];
        post?: never;
        /**
         * 게시물 삭제
         * @description 게시물을 삭제합니다.
         */
        delete: operations["deletePost"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/comments/{comment-id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 게시물 댓글 수정
         * @description 게시물의 댓글을 수정합니다.
         */
        put: operations["updateComment"];
        post?: never;
        /**
         * 게시물 댓글 삭제
         * @description 게시물의 댓글을 삭제합니다.
         */
        delete: operations["deleteComment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 회원 이름 검색
         * @description 회원 이름으로 회원을 검색합니다.
         */
        get: operations["searchMemberByName"];
        /**
         * 회원 정보 수정
         * @description 특정 회원의 정보를 수정합니다.
         */
        put: operations["updateMemberInfo"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 게시물 생성 및 요청
         * @description 게시물을 생성합니다.
         */
        post: operations["generatePost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{post-id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 게시물 댓글 조회
         * @description 게시물의 댓글을 조회합니다.
         */
        get: operations["getComments"];
        put?: never;
        /**
         * 게시물 댓글 생성
         * @description 게시물에 댓글을 생성합니다.
         */
        post: operations["createComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 회원가입
         * @description 회원가입을 완료합니다.
         */
        post: operations["join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/follows/{follow-id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 팔로우 요청 거절
         * @description 특정 팔로우 요청을 거절합니다.
         */
        post: operations["rejectFollowRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/follows/{follow-id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 팔로우 요청 수락
         * @description 특정 팔로우 요청을 수락합니다.
         */
        post: operations["acceptFollowRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/follows/members/{member-id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 팔로우 관계 확인
         * @description 특정 회원을 팔로잉 하고 있는지 확인합니다..
         */
        get: operations["getFollow"];
        put?: never;
        /**
         * 팔로우 요청
         * @description 특정 회원을 팔로우 요청합니다.
         */
        post: operations["requestFollow"];
        /**
         * 팔로우 취소
         * @description 특정 회원과 팔로우를 취소합니다.
         */
        delete: operations["cancelFollow"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat-rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 채팅방 목록 조회
         * @description 로그인한 사용자의 모든 채팅방 목록을 조회합니다.
         */
        get: operations["getChatRoomsByMember"];
        put?: never;
        /**
         * 채팅방 요청
         * @description 특정 회원과의 채팅방을 요청합니다. 채팅방이 없다면 새로 생성합니다.
         */
        post: operations["getChatRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 로그아웃을 수행합니다.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인
         * @description 회원 정보를 기반으로 로그인합니다.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email/code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 이메일 인증코드 전송
         * @description 이메일로 인증코드를 전송합니다.
         */
        post: operations["sendCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email/code/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 인증코드 유효성 확인
         * @description 인증코드의 유효성을 확인합니다.
         */
        post: operations["verifyCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 회원 정보 조회
         * @description 특정 회원의 정보를 조회합니다.
         */
        get: operations["getMemberInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{member_id}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 회원 게시글 조회
         * @description 특정 회원의 게시글을 조회합니다.
         */
        get: operations["getMemberPosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/follows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 팔로우 요청 조회
         * @description 내 팔로우 요청을 조회합니다.
         */
        get: operations["findMyFollow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/follows/members/{member-id}/followings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 팔로잉 조회
         * @description 특정 회원의 팔로잉을 조회합니다.
         */
        get: operations["getFollowings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/follows/members/{member-id}/followers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 팔로워 조회
         * @description 특정 회원의 팔로워를 조회합니다.
         */
        get: operations["getFollowers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat-rooms/{chat_room_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 채팅 조회
         * @description 채팅방의 채팅을 조회합니다.
         */
        get: operations["getChatMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PostRequest: {
            title?: string;
            content?: string;
            /** Format: int32 */
            "images-length": number;
        };
        CustomResponseBodyPostResponse: {
            message?: string;
            data?: components["schemas"]["PostResponse"];
        };
        ImageResponse: {
            url?: string;
        };
        MemberBriefResponse: {
            /** Format: int64 */
            member_id?: number;
            username?: string;
            real_name?: string;
            profile_image_url?: string;
        };
        PostResponse: {
            /** Format: int64 */
            post_id?: number;
            title?: string;
            content?: string;
            /** Format: date-time */
            create_at?: string;
            author?: components["schemas"]["MemberBriefResponse"];
            images?: components["schemas"]["ImageResponse"][];
        };
        CommentRequest: {
            content?: string;
        };
        CommentResponse: {
            content?: string;
            /** Format: int64 */
            postId?: number;
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            likeCount?: number;
            /** Format: int64 */
            reCommentCount?: number;
            /** Format: date-time */
            createdAt?: string;
            member?: components["schemas"]["MemberBriefResponse"];
        };
        CustomResponseBodyCommentResponse: {
            message?: string;
            data?: components["schemas"]["CommentResponse"];
        };
        ModifyRequest: {
            real_name?: string;
            profile_image_url?: string;
            introduction?: string;
            is_secret?: boolean;
        };
        CustomResponseBodyMemberDetailResponse: {
            message?: string;
            data?: components["schemas"]["MemberDetailResponse"];
        };
        MemberDetailResponse: {
            /** Format: int64 */
            member_id?: number;
            username?: string;
            real_name?: string;
            profile_image_url?: string;
            introduction?: string;
            /** Format: int64 */
            follower_count?: number;
            /** Format: int64 */
            following_count?: number;
            is_secret?: boolean;
        };
        JoinRequest: {
            /**
             * @description 회원가입할 사용자의 username
             * @example testUser
             */
            username: string;
            /**
             * @description 회원가입할 사용자의 password
             * @example password123
             */
            password: string;
            /**
             * @description 회원가입할 사용자의 realName
             * @example 테스트 유저
             */
            "real-name": string;
            /**
             * @description 회원가입할 사용자의 email
             * @example testUser@email.com
             */
            email: string;
        };
        CustomResponseBodyVoid: {
            message?: string;
            data?: unknown;
        };
        CustomResponseBodyString: {
            message?: string;
            data?: string;
        };
        CustomResponseBodyFollowResponse: {
            message?: string;
            data?: components["schemas"]["FollowResponse"];
        };
        FollowResponse: {
            /** Format: int64 */
            follow_id?: number;
            status?: string;
            follower?: components["schemas"]["MemberBriefResponse"];
            following?: components["schemas"]["MemberBriefResponse"];
        };
        ChatRoomRequest: {
            /** Format: int64 */
            recipient_id?: number;
        };
        ChatRoomResponse: {
            /** Format: int64 */
            chat_room_id?: number;
            last_chat?: string;
            members?: components["schemas"]["MemberBriefResponse"][];
        };
        CustomResponseBodyChatRoomResponse: {
            message?: string;
            data?: components["schemas"]["ChatRoomResponse"];
        };
        LoginRequest: {
            /**
             * @description 로그인할 사용자의 username
             * @example testUser
             */
            username: string;
            /**
             * @description 로그인할 사용자의 password
             * @example password123
             */
            password: string;
        };
        CustomResponseBodyMemberBriefResponse: {
            message?: string;
            data?: components["schemas"]["MemberBriefResponse"];
        };
        CodeRequest: {
            /**
             * @description 이메일 인증을 위한 이메일 주소
             * @example testUser@email.com
             */
            email: string;
        };
        VerifyRequest: {
            /**
             * @description 이메일 인증을 위한 이메일 주소
             * @example testUser@email.com
             */
            email: string;
            /**
             * @description 이메일 인증 확인을 위한 인증 코드
             * @example 123456
             */
            code: string;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        CustomResponseBodySliceCommentResponse: {
            message?: string;
            data?: components["schemas"]["SliceCommentResponse"];
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            paged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            unpaged?: boolean;
        };
        SliceCommentResponse: {
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["CommentResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            empty?: boolean;
        };
        SortObject: {
            empty?: boolean;
            sorted?: boolean;
            unsorted?: boolean;
        };
        CustomResponseBodySlicePostResponse: {
            message?: string;
            data?: components["schemas"]["SlicePostResponse"];
        };
        SlicePostResponse: {
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["PostResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            empty?: boolean;
        };
        CustomResponseBodySliceFollowResponse: {
            message?: string;
            data?: components["schemas"]["SliceFollowResponse"];
        };
        SliceFollowResponse: {
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["FollowResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            empty?: boolean;
        };
        CustomResponseBodySliceChatRoomResponse: {
            message?: string;
            data?: components["schemas"]["SliceChatRoomResponse"];
        };
        SliceChatRoomResponse: {
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["ChatRoomResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            empty?: boolean;
        };
        ChatResponse: {
            chat_id?: string;
            /** Format: int64 */
            chat_room_id?: number;
            /** Format: int64 */
            sender_id?: number;
            sender_username?: string;
            sender_real_name?: string;
            content?: string;
            created_at?: string;
        };
        CustomResponseBodySliceChatResponse: {
            message?: string;
            data?: components["schemas"]["SliceChatResponse"];
        };
        SliceChatResponse: {
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["ChatResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            empty?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "post-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodyPostResponse"];
                };
            };
        };
    };
    updatePost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "post-id": number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodyPostResponse"];
                };
            };
        };
    };
    deletePost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "post-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodyPostResponse"];
                };
            };
        };
    };
    updateComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "comment-id": number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodyCommentResponse"];
                };
            };
        };
    };
    deleteComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "comment-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodyString"];
                };
            };
        };
    };
    searchMemberByName: {
        parameters: {
            query: {
                username: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodyMemberBriefResponse"];
                };
            };
        };
    };
    updateMemberInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModifyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodyMemberDetailResponse"];
                };
            };
        };
    };
    generatePost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodyPostResponse"];
                };
            };
        };
    };
    getComments: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                "post-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodySliceCommentResponse"];
                };
            };
        };
    };
    createComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "post-id": number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodyCommentResponse"];
                };
            };
        };
    };
    join: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodyVoid"];
                };
            };
        };
    };
    rejectFollowRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "follow-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodyString"];
                };
            };
        };
    };
    acceptFollowRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "follow-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodyFollowResponse"];
                };
            };
        };
    };
    getFollow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "member-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodyString"];
                };
            };
        };
    };
    requestFollow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "member-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodyFollowResponse"];
                };
            };
        };
    };
    cancelFollow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "member-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodyString"];
                };
            };
        };
    };
    getChatRoomsByMember: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodySliceChatRoomResponse"];
                };
            };
        };
    };
    getChatRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRoomRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodyChatRoomResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodyVoid"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodyMemberBriefResponse"];
                };
            };
        };
    };
    sendCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodyVoid"];
                };
            };
        };
    };
    verifyCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodyVoid"];
                };
            };
        };
    };
    getMemberInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodyMemberDetailResponse"];
                };
            };
        };
    };
    getMemberPosts: {
        parameters: {
            query: {
                "cursor-id"?: number;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                member_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodySlicePostResponse"];
                };
            };
        };
    };
    findMyFollow: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodySliceFollowResponse"];
                };
            };
        };
    };
    getFollowings: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                "member-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodySliceFollowResponse"];
                };
            };
        };
    };
    getFollowers: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                "member-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodySliceFollowResponse"];
                };
            };
        };
    };
    getChatMessages: {
        parameters: {
            query?: {
                last_chat_id?: string;
            };
            header?: never;
            path: {
                chat_room_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomResponseBodySliceChatResponse"];
                };
            };
        };
    };
}
